"""The data layer: every table Seymour has, in one readable file.

The guide's Chapter 9 started with two tables (sessions, messages) and warned
against designing tables for features that don't exist yet. Every table below
exists because a shipped feature writes to it:

    sessions / messages  — chat history            (routes/chat.py)
    memories             — the RAG memory store     (memory/)
    agent_tasks          — the primary agent's jobs (agent/)
    agent_steps          — the agent's step journal (agent/loop.py)
    app_state            — tiny key/value: onboarding flag, active model, …
"""

# datetime for timestamps; timezone so they are never naive (see utcnow below).
from datetime import datetime, timezone

# The SQLAlchemy pieces we use. Text = unbounded string column type;
# ForeignKey = a column that references another table's primary key.
from sqlalchemy import ForeignKey, Text, create_engine, event
from sqlalchemy.orm import (
    DeclarativeBase,   # base class that registers our models
    Mapped,            # type annotation marker for mapped columns
    mapped_column,     # column definition helper
    relationship,      # ORM-level link between two tables
    sessionmaker,      # factory for database sessions
)

# All paths and knobs come from config — nothing here is hard-coded.
from seymour.config import settings


def utcnow() -> datetime:
    """Timezone-aware UTC. datetime.utcnow() is deprecated and, worse, returns
    a NAIVE datetime — one with no timezone attached — which silently compares
    wrongly against aware ones. Always store UTC; convert for display only."""
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    """SQLAlchemy's registry. Every model class inherits from this, which is
    how create_all() below knows what tables to make."""


# --------------------------------------------------------------------------- #
#  Chat                                                                       #
# --------------------------------------------------------------------------- #

class ChatSession(Base):
    """One conversation in the foreground chat."""

    __tablename__ = "sessions"

    # A UUID string, generated by the route when the conversation starts.
    id: Mapped[str] = mapped_column(primary_key=True)
    # Shown in the sidebar. Starts as the first message's opening words.
    title: Mapped[str] = mapped_column(default="New conversation")
    # What KIND of chat this started as: "chat" | "agent" | "research".
    # The OOP framing: every conversation is a chat; some are special
    # kinds of chat. The sidebar renders the matching symbol.
    kind: Mapped[str] = mapped_column(default="chat")
    # The job this chat most recently spawned (a discrete task's or a
    # research run's id) — how the sidebar knows the chat is LIVE in a
    # slot right now (labels carry the job id's first 8 chars).
    job_id: Mapped[str] = mapped_column(default="")
    created_at: Mapped[datetime] = mapped_column(default=utcnow)
    # onupdate=utcnow keeps this fresh automatically on every write.
    updated_at: Mapped[datetime] = mapped_column(default=utcnow, onupdate=utcnow)

    # The ORM half of the foreign key on Message:
    #   cascade="all, delete-orphan" → deleting a session deletes its messages
    #   order_by                     → messages always come back in order
    messages: Mapped[list["Message"]] = relationship(
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="Message.created_at",
    )


class Message(Base):
    """One turn in a conversation."""

    __tablename__ = "messages"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    # index=True because every message lookup filters by session_id. Without
    # it SQLite scans the whole table; with it, this stays fast at 10k rows.
    session_id: Mapped[str] = mapped_column(ForeignKey("sessions.id"), index=True)
    # Who spoke: "user" | "assistant" | "system".
    role: Mapped[str]
    # Text, not String: no length cap on a model's reply.
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(default=utcnow)

    session: Mapped[ChatSession] = relationship(back_populates="messages")


# --------------------------------------------------------------------------- #
#  Memory (the RAG store)                                                     #
# --------------------------------------------------------------------------- #

class MemoryEntry(Base):
    """One remembered fact, reviewable and deletable by the user.

    Retrieval works by embedding: `embedding` holds the entry's vector as a
    JSON array of floats, and memory/rag.py compares it against the query's
    vector by cosine similarity. Storing the vector next to the text keeps
    the whole memory system in one table you can inspect with sqlite3.
    """

    __tablename__ = "memories"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    # The remembered text itself — short, one fact per row.
    content: Mapped[str] = mapped_column(Text)
    # A coarse category shown in the UI: "fact" | "preference" | "note".
    kind: Mapped[str] = mapped_column(default="fact")
    # Where it came from: "user" (typed in), "agent" (saved by a tool call),
    # or "chat" (distilled from a conversation). Provenance builds trust.
    source: Mapped[str] = mapped_column(default="user")
    # The embedding vector as JSON text, e.g. "[0.12, -0.4, …]".
    # Text rather than a binary blob so `sqlite3` shows something readable.
    embedding: Mapped[str] = mapped_column(Text, default="[]")
    # Which embedder produced the vector ("llama" or "hashing"). Vectors from
    # different embedders are NOT comparable, so retrieval filters on this.
    embedder: Mapped[str] = mapped_column(default="hashing")
    # Pinned memories outrank retrieval: CORE pins (identity/contact) ride
    # in every chat; other pins are retrieved-before-ordinary. The Odysseus
    # lesson: importance is expressed structurally (pinned + category +
    # uses), not as a made-up numeric score.
    pinned: Mapped[bool] = mapped_column(default=False)
    # How many times this memory was actually INJECTED into a chat context
    # (retrieval alone doesn't count) — visible in the UI as "12×".
    uses: Mapped[int] = mapped_column(default=0)
    created_at: Mapped[datetime] = mapped_column(default=utcnow)


# --------------------------------------------------------------------------- #
#  The primary agent                                                          #
# --------------------------------------------------------------------------- #

class AgentTask(Base):
    """One job given to the primary background agent.

    The status field is the task's lifecycle state machine:

        queued → running → done | failed | cancelled
                    ↕
                 paused  (user asked, battery critical, …)
                    ↕
                 blocked (waiting for the user to approve an action)
    """

    __tablename__ = "agent_tasks"

    id: Mapped[str] = mapped_column(primary_key=True)   # a UUID string
    # What the user asked for, verbatim. The loop re-reads this every step.
    goal: Mapped[str] = mapped_column(Text)
    # Which kind of agent work this is:
    #   "primary" — the continuous background seat (Tier 3, one at a time,
    #               queued behind each other, often open-ended)
    #   "task"    — a discrete foreground job started from chat (Tier 2,
    #               several may run at once, expected to finish)
    kind: Mapped[str] = mapped_column(default="primary", index=True)
    # The lifecycle state — see the docstring diagram above.
    status: Mapped[str] = mapped_column(default="queued", index=True)
    # The chat this task was started from, if any — the organizer tabs
    # link back to it ("every task is a special kind of chat").
    session_id: Mapped[str] = mapped_column(default="")
    # The agent's own running notes: what it has learned/done so far. This is
    # the checkpoint that survives restarts — the loop rebuilds its prompt
    # from goal + notes + recent steps, so no context is lost when Seymour
    # (or the laptop lid) closes.
    notes: Mapped[str] = mapped_column(Text, default="")
    # Filled in when the task finishes: the agent's final report.
    result: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(default=utcnow, onupdate=utcnow)

    # The step journal, oldest first (see AgentStep).
    steps: Mapped[list["AgentStep"]] = relationship(
        back_populates="task",
        cascade="all, delete-orphan",
        order_by="AgentStep.id",
    )


class AgentStep(Base):
    """One entry in a task's journal — the agent's visible work log.

    Everything the agent does lands here, which is what makes the agent
    auditable: the UI renders this journal live, and after a restart the
    loop replays the recent tail to rebuild its context.
    """

    __tablename__ = "agent_steps"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    task_id: Mapped[str] = mapped_column(ForeignKey("agent_tasks.id"), index=True)
    # What kind of entry: "thought" | "tool_call" | "tool_result" |
    # "approval_request" | "approval_response" | "status" | "error".
    kind: Mapped[str]
    # The entry body. For tool calls/results this is JSON text; for thoughts
    # it is prose. Kept as Text so sqlite3 shows it directly.
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(default=utcnow)

    task: Mapped[AgentTask] = relationship(back_populates="steps")


# --------------------------------------------------------------------------- #
#  Runs and their event log (the harness rebuild's substrate)                 #
# --------------------------------------------------------------------------- #

class Run(Base):
    """One execution spawned by one user message (the rebuild's central
    primitive): policy is resolved PER MESSAGE at send time and recorded
    here — never latched onto the conversation.

    A run's whole story lives in its RunEvents; this row is the index
    card — preset, state, and summary stats for lists and filters.
    """

    __tablename__ = "runs"

    id: Mapped[str] = mapped_column(primary_key=True)     # uuid4 string
    session_id: Mapped[str] = mapped_column(index=True)   # its conversation
    # Which policy preset resolved for this message: "chat" | "deep_research".
    preset: Mapped[str] = mapped_column(default="chat")
    # running | done | failed | cancelled  (approval states arrive with
    # the write-gating increment).
    status: Mapped[str] = mapped_column(default="running")
    # Summary stats as JSON text (tool_calls, tokens, seconds, outcome
    # details) — filled once at completion; the per-step truth is events.
    stats: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(default=utcnow)
    finished_at: Mapped[datetime | None] = mapped_column(default=None)

    events: Mapped[list["RunEvent"]] = relationship(
        back_populates="run", cascade="all, delete-orphan",
        order_by="RunEvent.seq")


class RunEvent(Base):
    """One typed entry in a run's append-only event log.

    THE source of truth for traceability: everything the run did — each
    model call, each tool call with its payload and result, each policy
    decision — appends here as it happens, and the trace UI is a straight
    read of this table (never a parallel bookkeeping path). Types:
    "run_start" | "model_call" | "model_result" | "tool_call" |
    "tool_result" | "repair" | "note" | "run_end".
    """

    __tablename__ = "run_events"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(ForeignKey("runs.id"), index=True)
    seq: Mapped[int]                          # order within the run
    type: Mapped[str]
    # The payload as JSON text. Bounded at write time (BIG tool results
    # are excerpted with their true length noted) — the log must stay
    # cheap to read forever.
    data: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(default=utcnow)

    run: Mapped[Run] = relationship(back_populates="events")


# --------------------------------------------------------------------------- #
#  Uploads and the gallery                                                    #
# --------------------------------------------------------------------------- #

class Upload(Base):
    """One file the user attached in chat — document or image.

    The bytes live on disk under uploads/; this row is the ledger: what it
    was called, what type it is, and (for documents) the extracted text so
    a re-attach never re-parses. Images additionally join the gallery.
    """

    __tablename__ = "uploads"

    id: Mapped[str] = mapped_column(primary_key=True)      # a UUID string
    # The stored filename (uuid + original extension), inside uploads/.
    filename: Mapped[str] = mapped_column(unique=True)
    # The user's original name — what the UI shows on the chip.
    original_name: Mapped[str] = mapped_column(default="")
    # "image" | "document" — decides how chat injects it.
    kind: Mapped[str] = mapped_column(default="document")
    # The declared/derived MIME type (image/png, application/pdf, …).
    mime: Mapped[str] = mapped_column(default="")
    # For documents: the extracted text (bounded), ready for guard-wrapping.
    text: Mapped[str] = mapped_column(Text, default="")
    size_bytes: Mapped[int] = mapped_column(default=0)
    created_at: Mapped[datetime] = mapped_column(default=utcnow)


class GalleryImage(Base):
    """One image in the gallery — every image that passes through Seymour.

    A compact adaptation of Odysseus's gallery schema (see
    ACKNOWLEDGMENTS.md): enough to browse, name, favorite and delete, and
    nothing speculative.
    """

    __tablename__ = "gallery_images"

    id: Mapped[str] = mapped_column(primary_key=True)      # a UUID string
    # The stored filename inside the gallery directory.
    filename: Mapped[str] = mapped_column(unique=True)
    # The display name (defaults to the original upload name).
    name: Mapped[str] = mapped_column(default="")
    # Where it came from: "chat-upload" for now (generation may come later).
    source: Mapped[str] = mapped_column(default="chat-upload")
    # The chat session it arrived in, if any (loose link, no FK cascade).
    session_id: Mapped[str] = mapped_column(default="")
    favorite: Mapped[bool] = mapped_column(default=False)
    created_at: Mapped[datetime] = mapped_column(default=utcnow)


# --------------------------------------------------------------------------- #
#  App state                                                                  #
# --------------------------------------------------------------------------- #

class AppState(Base):
    """A tiny key/value table for one-off application state.

    Used for: "onboarding_done" (first-launch tour), "active_model" (which
    .gguf the engine should load), and similar single values. A dedicated
    table per flag would be ceremony; a config file would be a second source
    of truth next to the database. One k/v table is the honest size.
    """

    __tablename__ = "app_state"

    key: Mapped[str] = mapped_column(primary_key=True)
    value: Mapped[str] = mapped_column(Text)


# --------------------------------------------------------------------------- #
#  Engine and session factory                                                 #
# --------------------------------------------------------------------------- #

# check_same_thread=False: SQLite defaults to refusing use from a thread other
# than the one that opened it. Our handlers are async (event-loop thread) but
# hot paths push DB work into worker threads via asyncio.to_thread, so
# connections legitimately move between threads. Safe here because we open
# a fresh session per request and never share one across concurrent work.
engine = create_engine(
    f"sqlite:///{settings.db_path}",
    connect_args={"check_same_thread": False},
)


@event.listens_for(engine, "connect")
def _tune_sqlite(dbapi_connection, _record) -> None:
    """Per-connection SQLite pragmas — the three that matter here.

    - WAL journaling: writers stop blocking readers, and commits become
      cheap appends instead of full-database fsync dances. This is what
      keeps a journal write from freezing every live token stream (all
      our async handlers share one event-loop thread).
    - synchronous=NORMAL: the safe pairing with WAL — durable against
      app crashes, losing at most the final commit in an OS-level crash.
      A chat app on a laptop takes that trade happily.
    - foreign_keys=ON: SQLite ships with FK enforcement OFF; without this
      a journal row for a deleted (or never-existing) task id inserts
      silently instead of failing loudly.
    """
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA journal_mode=WAL")
    cursor.execute("PRAGMA synchronous=NORMAL")
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.close()

# expire_on_commit=False: after commit(), objects keep their loaded values
# instead of being expired and re-fetched — which matters because we often
# read attributes (like a new session's id) after the session block closes.
SessionLocal = sessionmaker(bind=engine, expire_on_commit=False)


# Columns added to EXISTING tables after v1 shipped. create_all() only
# creates missing TABLES, so these few need explicit ALTERs on databases
# created before the column existed. (table, column, DDL type+default).
_LATE_COLUMNS: list[tuple[str, str, str]] = [
    ("agent_tasks", "kind", "VARCHAR DEFAULT 'primary'"),
    ("agent_tasks", "session_id", "VARCHAR DEFAULT ''"),
    ("memories", "pinned", "BOOLEAN DEFAULT 0"),
    ("memories", "uses", "INTEGER DEFAULT 0"),
    ("sessions", "kind", "VARCHAR DEFAULT 'chat'"),
    ("sessions", "job_id", "VARCHAR DEFAULT ''"),
]


def init_db() -> None:
    """Create tables if they don't exist, and add late columns. Idempotent
    — safe on every startup.

    Not a real migration system — just create_all() plus a short list of
    ALTER TABLE ADD COLUMN statements for columns that arrived after v1
    (SQLite adds columns in place, cheaply). Fine for one developer on
    one laptop; anything structural still means migrating by hand.
    """
    Base.metadata.create_all(engine)
    with engine.connect() as connection:
        for table, column, ddl in _LATE_COLUMNS:
            # Ask SQLite what columns the live table actually has…
            have = {row[1] for row in
                    connection.exec_driver_sql(f"PRAGMA table_info({table})")}
            # …and add the column only if a pre-upgrade database lacks it.
            if have and column not in have:
                connection.exec_driver_sql(
                    f"ALTER TABLE {table} ADD COLUMN {column} {ddl}")
        connection.commit()


# ---- App-state helpers (the whole API the k/v table needs) ----------------- #

def get_state(key: str, default: str | None = None) -> str | None:
    """Read one value from app_state, or `default` if the key is absent."""
    with SessionLocal() as db:
        row = db.get(AppState, key)
        return row.value if row else default


def set_state(key: str, value: str) -> None:
    """Write one value to app_state, inserting or overwriting as needed."""
    with SessionLocal() as db:
        # merge() = insert-or-update by primary key, in one call.
        db.merge(AppState(key=key, value=value))
        db.commit()
