/** scenes.ts — the two full scenes Seymour lives in, cell for cell.
 *
 * Both were EXTRACTED from Nick's reference art (the framed "monster at
 * the computer" and "tea break, feet on the desk" images): each source's
 * screen area was located inside its bezel, every pixel classified by
 * tone + region (flood fill on a dilated ink mask, enclosed components,
 * furniture zones), and the result voted into 7px cells — so the scenes
 * ARE the references. Regenerate with scripts/extract_scenes.py if the
 * reference art ever changes.
 *
 * One character per cell, mapped onto the live palette at draw time:
 *   '.' wall (transparent — the canvas paper + dot texture shows)
 *   'k' monster ink   'i' furniture ink   'g' floating strokes (steam)
 *   'b' body          's' body shade      'w' white (eyes/teeth/cup)
 *   'o' horn          'd' horn ridge      't' tongue
 *   'f' furniture fill  'm' furniture mid
 */

/** One extracted scene: the grid plus its measured face anchors. */
export interface Scene {
  w: number;                     // grid width in cells
  h: number;                     // grid height in cells
  eyes: [number, number][];      // the three eye centers, in cells
  mouth: [number, number, number, number];  // erasable mouth box [x0,x1,y0,y1]
  deskline: number;              // the desk edge row (composition anchor)
  rows: string[];                // h strings of w cells
}

/** Seymour typing at the CRT — every state where he is at work
 *  (working / waiting / blocked / sleeping wear their poses on it). */
export const DESK_SCENE: Scene = {
  w: 151, h: 112,
  eyes: [[80, 52], [93, 52], [107, 52]],
  mouth: [70, 102, 60, 74],
  deskline: 90,
  rows: [
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    ".......................................................................................................................................................",
    ".......................................................................................................................................................",
    ".......................................................................................................................................................",
    ".......................................................................................................................................................",
    ".......................................................................................................................................................",
    ".......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i......................................................................................................................................................",
    "i..............................................................................................iik.....................................................",
    "i............................................................................kk................ikkk...................iik..............................",
    "i...........................................................................kkkk...............ikbkk..i...............kkkk.............................",
    "...........................................................................koodk............ii.kkbkkkkki..............kookk............................",
    "..........................................................................kkookk............kkkkkbbkkkki..............koookk...........................",
    "..........................................................................koodk.............kkkksbbkkski..............kooodk...........................",
    "..........................................................................koodk.............kkkbsbbkbkkk..............kdoddk...........................",
    ".........................................................................kdoook.........kkkkkkkbbssbskkkkkk...........koooddk..........................",
    ".........................................................................kooookk.....kkkkkbbbskksbsskkbbbbkkkk........koooodk..........................",
    ".........................................................................koookkdk..kkkbbbbbbbbbssbssbbbbbbbbbskkk....kkoooodk..........................",
    ".........................................................................koodookkkikbbbbbbbbbbbbbbbbbbbbbbbbbbbskkk.kkooooddk..........................",
    ".........................................................................koddoookkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkkkdooodddk..........................",
    ".........................................................................kdoooddksbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbskkoooooodkk..........................",
    "..........................................................................kdoodkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbskkoodddddk...........................",
    "..........................................................................kdddkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkoodkkkk...........................",
    "...........................................................................kkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkddkkkk............................",
    "...........................................................................kkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkdkkk............................",
    "...........................................................................kkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbskkkk.............................",
    "...........................................................................kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssskk............................",
    "..........................................................................kkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssk............................",
    "..........................................................................kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssskk...........................",
    ".........................iiii.............................................kbbbkkkkbbbbbbbbbbbbbbbbbbbbbbbkkkkbbbbbbbbbbssskk...........................",
    ".......................iifffwiiiiiiiii...................................ksbbkbbbkkbbbbbbbbbbbbbbbbbbbbbksbbbkbbbbbbbbbbbssk...........................",
    "......................iiffffffffffffffiiiiiiiiii.........................kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsskk..........................",
    ".....................iiiiffffffffffffffffffffffiiiiiiii..................kbbbbbbbbbbbbbbbbbssbsbbbbbbbbbbbbbbbbbbbbbbbbbbsssk..........................",
    ".....................iiiiiiiifffffffffffffffffffffffffii................kkbbbkkkkkkbbbbbbbkkkkkkbbbbbbbbkkkkkbbbbbbbbbbbbsssk..........................",
    "..................iiifffffffmiiiiiiiiiiiffffffffffffffii...............iksbbkwwwwwkkbbbbskkwwwwkkbbbbbskwwwwwkkbbbbbbbbbbbssk..........................",
    ".................iiwfffffffffffffffffffiiiiiiiiiiffffffi...............ikbbkwwwwwwwkkbbbkwwwwwwwkkbbbkkwwwwwwwkkbbbbbbbbbbsskkk........................",
    "................iifffffffffffffffffffffffffffmiiifffffffi..............ikbskwwwwwwwwksbkwwwwwwwwwksbskwwwwwwwwwkbbbbbbbbbbssski........................",
    "..............iiifffffffffffffffffffffffffffffffiifffffmi..............kkbkwwwkkwwwwkkbkwwwwwwwwwkkbskwwwwwwwwwksbbbbbbbbbssski........................",
    ".............iifffffffffffffffffffffffffffffffffiifffffmi.............kksbkwwwkkkwwwwkkwwwwkkkwwwwkskwwwkkkwwwwwkbbbbbbbbbssski........................",
    "............iifffffffffffffffffffffffffffffffffffiffffffi.............ikbbkwkkwkikwwwkkwwkkwkkkwwwkskwwkwkikwwwwkbbbbbbbbbssskk........................",
    "............iifffffffffffffffffffffffffffffffffffiffffffi.............ikbbkwkkkiikwwwkkwwkkkiikkwwkskwwkkkiikwwwkbbbbbbbbbsssskk.......................",
    "............iifffffffffffffffffffffffffffffffffffiffffffi.............ikbbkwkkiiikwwwkkwwkiiiikkwwkskwwkiiiikwwwkbbbbbbbbbsssskiiiii...................",
    "............iifffffffffffffffffffffffffffffffffffiffffffi.............ikbbkkwkkikkwwwkkwwwkiikkwwwkbkwwkkiikkwwwkbbbbbbbbbsssskimmmiiiii...............",
    "............iifffffffffffffffffffffffffffffffffffiffffffi.............ikbbskwwkkkwwwksbkwwwkkkwwwkkbkkwwkkkwwwwksbbbbbbbbbsssskiiimmmmmiii.............",
    "............iifffiiifffffffffffffffffffffffffffffiffffffi.............ikbbbkkwwwwwwwkbbkkwwwwwwwwkbbbkwwwwwwwwwkbbbbbbbbbbsssskiiimmmmmmmi.............",
    "............iifffffiiiiiimfffffffffffffffffffffffiffffffi.............ikbbbbkkwwwwkksbbbkkwwwwwwkkbbbkkwwwwwwwksbbbbbbbbbbsssskiiimmmmmmmmi............",
    "............iifffffffffmiiiiiiiifffffffffffffffffimffffffi............ikbbbbbkkkkkksbbbbskkkkkkkkbbbbskkwwwwwkkbbbbbbbbbbbsssskiiimmmmmmmmi............",
    "............iifffiiiiiiffffffffifffffffffffffffffiiffffffi............ikbbbbbbbkkbbbbbbbbbskkkkbbbbbbbbkkkkkkbbbbbbbbbbbbbsssskkiiimmmmiimi............",
    "............iiffffmiiiiiiiiiiifffffffffffffffffffiiffffffi............ikbbkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkbbbbbbbbbssssskiiimmmmiiii............",
    "............iifffiimfffmiiiiiiiifffffffffffffffffiiffffffi...........kkbbkbbkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbssssskiiimmmmiiii............",
    "............iifffiiiiiiiiiffffiifffffffffffffffffmiffffffi...........ifffkfffffffkkkbbbbbbbbbbbbbbbbbbbbbbbbbbkbbkkbbbbbbbssssskiiimmmmiimi............",
    "............iifffifffiiiiiiiiiiiffffffffffffffffffiffffffi...........kffffkkfffffkkkkkkkbbbbbbbbbbkkkbbbbbbbbbbbkbbbbbbbbbssssskiiimmmmimmi............",
    "............iifffiiimfffffffiiiiffffffffffffffffffiffffffi..........ikfffffffffffkkkttkkkkkkkkkkkkttkbbbbbbbbbbbkbbbbbbbbbssssskkiimmmmimmi............",
    "............iifffmiiiiiiiimmffffffffffffffffffffffiffffffii........ikffffffffffffkkkkkktttttttttttkkkbbbbbbbbbbbbbbbbbbbbbssssskkiimmmmimmi............",
    "............iifffiffffffiiiiiiiiffffffffffffffffffifffffffi........kfffffmffffffffkiiiikkkkkkkkkkkikkbbbbbbbbbbbbbbbbbbbbbsksssskiimmmmimmi............",
    "............iifffiiiiiiifffffffiffffffffffffffffffiiffffffi......ikffffffkmffffffffkiiiiiiiiiiiiiiikbbbbbbbbbbbbbbbbbbbbbssssssssiiimmmimmi............",
    "............iiffffffmiiiiiiiiiimffffffffffffffffffiiffffffi.....ikbbbbbbsskbbbbbbbbkkiiikkkkkkkkiikbbbbbbbbbsbbbbbbbbbbbbssssssssiiimmmimii............",
    "............iifffiiiiifffffiiiiiffffffffffffffffffiiffffffi....kkbbbbbskkkksbbbbbbbbkkikkttttttkkkkbbbbbbbbksbbbbbbbbbbbbssssssssiiimmiimii............",
    "............iiffffiiiiiiiimffffffffffffffffffffffffiffffffi...ikbbbbbbbbbsksbbbbbbbbbbkkkkttttkkksbbbbbbbskksbbbbbbbbbbbsssssssssiiimmimmi.............",
    "............iiffffffffffmiiiiiiifffffffffffffffffffiffffffi..ikbbbbbbbbbbbsksbbbbbbbbbbskkkkkkkbbbbbbsskkkkbbbbbbbbbbbbsssssssbssiiimmimmi.............",
    "............iiffffffffffffffffiifffffffffffffffffffiffffffi..kwbbbbbbbbbbbskkbbbbbbbbbbbbbbbbbbbbskkkkkkbbbbbbbbbbbbbbbssssskssssiiimmimmi.............",
    "............iiffffffffffffmffffffffffffffffffffffffiffffffi.ikbbbbbbbbbbbbbskbbbbbbbbbbbbbbbbbskkksbbbbbbbbbbbbbbbbbbbssssssssbssiiimmimmi.............",
    "............iifffffffffffffffffffffffffffffffffffffiffffffi.kbbkbbsbbbbsbbbsksbbbbbbbbbbbbbbbskkbbbbbbbbbbbbbbbbbbbbbssssssssssskiiimmimmi.............",
    "............iifffffffffffffffffffffffffffffffffffffiifffffi.kbkbbbkbbskkbbbskssbbbbbbbbbbbbbbkkbbbbbbbbbbbbbbbbbbbbbbssssssssssskiiimmimmi.............",
    "............iiiffififffffffffffffffffffffffffffffffiifffffi.kbkbbkbbbkksbbsskssbbbbbbbbbbbbbkkbbbbbbbbbbbbbbbbbbbbbbsssssssssssskiiimmimmi.............",
    ".............iiffififfffiiiffffffffffffffffffffffffiiffffii.kkkbbkbbskkbbsskisssbbbbbbbbbbbskbbbbbbbbbbbbbbbbbbbbbbssssssssssssskiiimmimmi.............",
    ".............iiifffffffiiiiifiiiiffffffffffffffffffiifiiii...ikkskssskiikkkiisssssssbbbbbbbksbbssbbbbbbbbbbbbbbbssssssskkssssssskiiimmimmi.............",
    "...............iiiifffiiiiiifiiiifffffffffffffffffiiiiiik...iiiikikkkiffiiiiikkkkksssssbbsskbbskkbbbsbbbbbbbbbbsssssssksssssssskkiiimmimii.............",
    "................iiiiiiiiiiifffffiffffffffffffffiiiiiii....iifwfifmiikiiiiffwffffmikkkkssssskbskkbbbskbbbbsssssssssssskksssssssskiiiimiimii.............",
    "...............iiiiiiiiiiiiiiiiffffffffffffiiiiiiiiikkkiiiiiiiiiiiiiiimkkkiikiiifffffikkkkkkkskkbbskkbbbsskkssssssskkkssssssssskiiiimimmi..............",
    "miiiiiiiiiiiiiiiiffffiiiifffiiiiiiiffmffiiiiiiiiifiiiiiiifffiifiiiiiiwkkbbkkbbkkkkiiffffffiikkkkbbskbbbssskkssssskkikkskkssssskiiiiimimii..............",
    "iiiiiiiiiiiiiiifffffmiiiffffffffiiiiiiiiiiiifmffffffffiiiiiiffiffwifiiikkkkwbbkwbbkkiiiiiiffikkksskksssskkikkkkkkkkiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
    ".............ifffffffiifffffffffffiiiiiimfffffffffffffffkbkkkkiiiifiifffkbbbkiiikkbkwfimfiiikbbkkkkkkskkkkkkkkkkkks....................................",
    ".............iffffffiiiffffffffffffffffffffffffffffffffmibbbbbbbkkiiiiiiwbbkffffififiiiiiikkbbbkbbkkkkkkkkwbkbbbkki....................................",
    ".............ifffffmiiiffffffffffffffffffffffffffffffffmibbbbbbbbbbbbbkkkkkkiiiiiffmiffffkkbbkkbbksbbbbkkkbkbbbbbki....................................",
    ".............ifffffiiiifffffffffffffffffffffffffffffffffibbbbbbbbbbbbbbbbbbbbbkkkkkkiiiiikbbbbbkkbkkkbkbbbkbbbbbbki....................................",
    ".............ifffffffiiiffffffiffffffffffffffffffffffffmikkkkkbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkbbkbbbbkbbbbkkbbbbbbbki....................................",
    ".............iiiffffmiiimfffffiiiiiiffffffffffffffffffffiiiiiikkkkkbbbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkkkkkkkbbbbbbbbki....................................",
    "ffffffffffffffiiiiimffiiifffffiffiiiiiffffffffffffffffiiiiiiiikiikkkkkkkksbbbbbbbbbbbbbbbbbbbbbkkkkkkkkkbbbbbbbkkkiffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffiiiiiiiiiffffiiiiifffffffffffffffffiiiiiiiiiifffffiiikkkkkkkkkkbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkfffffffffffffffffffffffffffffffffffffff",
    "ffffffffffffffffffffiiiiiiiimffmffiiiiffffffffffiiiiiifffffffffffffffffffiiiiiikkkkkkkbbbbbbbbbbbbbbsbbbbbsbkkkffffffffffffffffffffffffffffffffffffffff",
    "ffffffffffffffffffffffffiiiiiiiimffffifffffffiiiiiifffffffffffffffffffffffffffffffkkikkkkkksbbbbbbbbbbbbbbkkiffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffiiimmmiiiiiiimfffiiiiiiffffffffffffffffffffffffffffffffffffffffkkikkkkkkkbbbbsbskiffffffffffffffffffffffffffffffffffffffffffff",
    "ffffffffffffffffffffffffffiiiiimmmmmiiiiiiifffffffffffffffffffffffffffffffffffffffffffffffffffiiiiikkkkkkffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffiiiiiiiiiiiiiiffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffiiiiffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "iffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "iffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
  ],
};

/** Feet on the desk, cup in paw — the loaded-but-idle scene (and the
 *  after-work tea break; both are the same well-earned recline). */
export const TEA_SCENE: Scene = {
  w: 132, h: 180,
  eyes: [[76, 74], [87, 74], [98, 75]],
  mouth: [75, 110, 86, 102],
  deskline: 165,
  rows: [
    "..iiii.......................................................................................................................kkk....",
    "..mi................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "..mi................................................................................................................................",
    "..ii................................................................................................................................",
    "..ii................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "...m................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "...i................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "..............................................................................kk....................................................",
    "............................................................................kkok....................................................",
    "...........................................................................kdokk.............................k......................",
    "..........................................................................koook..............kk.............kok.....................",
    ".........................................................................kkoook..............kkk............kdok....................",
    ".........................................................................kooddk..........kkkskbk.............kwok...................",
    "...i.....................................................................dooodk..........kskksskkkkk.........kwodk..................",
    "...i....................................................................koooook..........kbbkbsskkk..........koodk..................",
    "........................................................................koooodkk......kkkksbsbskksk..........dddddd.................",
    "........................................................................kdooddok..kkkksbsssbbsssskkk........kowoddk.................",
    "........................................................................kdddoddkkksbbbbbbbssssssskkkkk......kwwbbsk.................",
    "........................................................................kkdoookkswbbbbbbbbbbbbbbbbbsskkk...ksswwbsk.................",
    "...i.....................................................................kddkkwbbbbbbbbbbbbbbbbbbbbbbbsskkkkbbssssk.................",
    ".........................................................................kkkkwbbbbbbbbbbbbbbbbbbbbbbbbbbskksbwbsskk.................",
    "..........................................................................kwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkbsbsssk..................",
    ".........................................................................kwwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbskssssskk..................",
    "........................................................................kswbsssbbbbbbsssbbbbbbbbbbbbbbbbbbsksssskk..................",
    ".......................................................................ksbssbssbbbbbbsbbsbbbbbbbsssbbbbbbbbskkskk...................",
    ".......................................................................kwbssbbbbbbbbbbbbbbbbbbbsssssbbbbbbbsskkkk...................",
    "......................................................................kbbbssbsbbbbbbbbbbbbbbbbbbbbbsbbbbbbbbsssskk..................",
    ".....................................................................kkbbskswkbbbbbbskkwbbbbbbbbbbbbbbbbbbbbbssssk..................",
    ".....................................................................kbbskwwwwksbbbkswwwkwbbbbskkkwbbbbbbbbbbssssk..................",
    ".....................................................................sbskwwwwwwksbkswwwwwkwbbskswwwkwbbbbbbbbssssk..................",
    "....................................................................kkbkwwwwwwwwsskwwwwwwwkbskwwwwwwkwbbbbbbbbssssk.................",
    "....................................................................kwssbwkkkwwwskbwwwwwwwwskbbwwwwwwkbbbbbbbbssssk.................",
    "....................................................................kskbwkwkkwwwkkwwwkkwwwwkswbwwwwwwwsbbbbbbbsssski................",
    "....................................................................kbkbwkkiikwwkswwkkkkwwwkwwwkkkwwwwkbbbbbbbsssssk................",
    "...................................................................skbkbwkkikkwwkswwkiikwwwkwbkkikwwwwkbbbbbbbssssskiiii............",
    "...............iiii.......................................kkkkkkk..ksbkbwwkkkwwwkswwkkkwwwwkwwkiikwwwwkbbbbbbbssssskmfiii...........",
    ".............mimfffiiiii............................iiifkksbbbbbbskkbbsswwwwwwwkkkbwwwwwwwskwwwkkkwwwwkbbbbbbbssssskmmffmi..........",
    "............iifffffffffmiiiii......................ifffksssssssssswskbbkbwwwwwskskbwwwwwwskkbwwwwwwwwskbbbbbbbssssskmmmffmi.........",
    "...i.......imfffffffffffffffmiiiii...............iiiiiiwkkkkkkkkkkkwkbbskswwwbkkbskbwwwwsksskwwwwwwwsksbbbbbbbssssskmmmmfmii........",
    "..........iiiiiimffffffffffffffffmiiiii.........iifffmissswwwwwwwssskbbbskkkkkssbbskswwskkbbkswwwwwsksbbbbbbbbssssskimmmmmmi........",
    ".........imfffffmiiimfffffffffffffffffii........iffffffksbsssssssssskbbbbssksssbbsbskkkkssbbskkbwbsksbbbbbbbbsssssskimmmmmmi........",
    ".......iifffffffffffmiiiimiffffffffffffi........wffffffisbsbbbbbbssskssbbbbbbbbbbbbbskksbbbbbbskkkksbbbbbbbbbbssssskimmmmmmi........",
    "....miiffffffffffffffffffiiiimiifffffffmi......ifffiiiikswsbbbbbbssskbbbbbbbbbbbbbbbbbbbbbbbbbsssssbbbsbbbbbbsssssskimmmmmmi........",
    "....imffffffffffffffffffffffffffimffffffi......iffffffiksssbbbbbssskkbsbbbbbbsbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssskimmmfmmi........",
    "....mfffffffffffffffffffffffffffmiffffffi......ifffffffissbbbbbssssksbbbbbbbbkksbbbbbbbbbbbbbbbbbbbbsbbbsbbbbsssssskimmmfmmi........",
    "....mmfffffffffffffffffffffffwfffiffffffi......ifffffffikssbbbssssskbbbbbbbbbkkkkkssbbbbbbsskksbbbbbbbbbbbbbbsssssskimmmmmmi........",
    "...immmmmmwwfffffffffffffffwfffffiffffffi......ifffimiiiksssssssssksbbbbbbbbbkiiiikkkkkkkkkkkkbbbbbbbbsbbbbbbbbsskkkimmmmmmi........",
    "..mmmmmmmmmmmmmffffffffffffffffffiffffffi......imffffffimikssssskkssbbbbbbbbbbkiiikkkkkkkkikkbbbbbbbbbbbbbbbbbbbbskkimmmimmi........",
    "....mmmmmmmmmmmmmmmfwffffffffffffiwfffffi......miffffffimiiikkkkkssbbbbbbbbbbbkkikksssssskkkbbbbbbbbbbbbbbbbbbbbbbskimmfimmi........",
    "....immmmmmmmmmmmmmmmwfffffffffffiwfffffi.......iffmffmiiimmmkssssbbbbbbbbbbbbbkkssssssssskbbbbbbbbbbbbbbbbbbbbbbbsskmmfimii........",
    "....mmmmmmmmmmmmmmmmmwfffffffffffiffffffi.......iffmiiimmmmmisssbbbbbbbbbbbbbbbbsksssssskkbbbbbbbbbbbbbbssbbbbbbbbbskimmimi.........",
    "..immmiiiimmmmmmmmmmmffffffffffffiffffffi.......smfmmmmmmmmiksbbbbbbbbbbbbbbbbbbbbskkkkkbbbbbbbbbbbbbbbssssbbbbbbbbbskmmmmi.........",
    "..iimmmiiiiiiimmmmmmmffffffffffffiffffffi........iiimmmmmmmisbbbbbbbbbbbbbbbbbbbsssssssbbbbbbbbbbbbbbbssskssbbbbbbbbbkiimmi.........",
    "....mmfmmmiiiiiiiimmmffffffffffffiwfffffi......kkkbbiiiiimikbbbbbbbbbbbbbbbbbbbbbbsssssbbbbbbbbbbbskkkkkkkkkssbbbbbbbskimmi.........",
    "....mmiiiimmffmiiimmmffffffffffffiwfffffi.....kkksbbskwssiibbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbskksbbbbbbsskksbbbbbbskimii.........",
    "....mmfmmiiimmmmfmmmmffffffffffffiwfffffm....kwbssbbkwbbbkksbbbbbbbbkkkbbbbbbbbbbbbbbbbbbbbbbbbkksbwbbsbbbbbwbsbbbbbbssimi..........",
    "....mmmmffmiiiimmmmmmffffffffffffiwfffffii...kbbkkssksbbssksbbbbbkkkkbbkbbbbbbbbbbbbbbbbbbbbbbksbbbbbbbbbbbbbbbsbbbbssskmi..........",
    "....mmmiiimfmmmiiimmmffffffffffffiwffffffi..kkbssksssksssskssbbbkwbkbbbkkkbbbbbbbbbbbbbbbbbbbksbbbbbbbbbbbbbbbbbbbbbssskmi..........",
    "....mmmmmiiiiiimmmmmmffffffffffffiwffffffi.kksksssbbsbsksskkssbkwbbsbbsswbksbbbbbbbbbbbbbbbbksbbbbbbbbbbbbbbbbbbbbbsssskii..........",
    "....mmiiiimfmmiiiimmmffffffffffffiwffffffi.kbbsbbbbbbbbbsssksssksssksskbbbsksbbbbbbbbbbbbbbskwbbbbbbbbbbbbbbbbbbbbbsssskii..........",
    "....mmmmiiiiimmmmmmmmffffffffffffifffffffi.ksssbbbbbbbbbbsskksssksbbbsksbsskkbbbbbbbbbbbbbbkssssbbbbbbbbbsbbbbbbbssssskiii..........",
    "....mmmimffmiiiimmmmmffffffffffffmfffffffi..kssbbbbbbbbbbsssssskbwbbbbbsksbbskbbbbbbbbbbbbbksskbbbssbbbbsssssssssssssskiii..........",
    "....mmfiiiiiimmiiimmmffffffffffffmfffffffi...kbbbbbbsssbbsssskskbbbbbbbbssbbskksbbbbbbbbbbbkssswbssbbbssssssssssssssskkski..........",
    "....mmmmmmfmiiiimmmmmfwffffffffffmmffffffi...kbbbbbsssssbsssskksbbbbbbbbbsssskbksbbbbbbbbbbskksssksbbssssssssssssssskkkskk..........",
    "....mmmiiiimffmiiimmmffffffffffffmmffffffm...ksbbbsssssssssssskbbsbbbbbbbskskbbbksbbbbbbbbssskssskbbsssskkssssssskkkkssskk..........",
    "....mmmmmmiiiiimmfmmmmffffffffffffiffffffi...ksbbssssssbsssssskbssssbbbbbbbskbbbssbbbbbbbsssskkksksssskkkkkkkkkkkkkssssskk..........",
    "....mmmmmmmmmiiiimmmmmffffffffffffiffffffi....kssbssssssbssssskssssssbbbbbbsksbbbsssssssssssssskkkkkkkkkssssssssssssssssk...........",
    "....mmmmmmiimfmmmmmmmmffffffffffffiffffffi....ksbsssssssbbssssksssssssbbbbbskssbbsssssssssssssskksssksssssssssssssssskkki...........",
    "....mmmmmfmmmimmmmmmmmffffffffffffiffffffi.....kssssssssbbsssssksssssbbbbbssksssssssssssssssssskbssssssssssssssssskkkiii............",
    "....mmmmmmmmmmmmmmmmmmwfffffffffffiffffffimikiiisssssssssbssssksbsssssbbbbssksssssssssssssssssksssssssbsssssssskkkkiiimi............",
    "....mmimimmmmmmmmmmmmmwfffffffffffmmfffffiifffffksbssssssbssssksbsssssbbbbsssssssssssssssssssskssssssssssskkkkiiikiiimmi............",
    "....immiimmmiimmmmmmmmfffffffffffffiffffffifffffisssbbsssssssskbssssssbbbbsssssssssssssssssssskssssssssskkkiiiikkkkimmmi............",
    "....immmmmmiiimmimmmmmfffffffffffffiffffmiifffffmissssssssskkkkbsssbbbsbbssssssssssssssssssssksssssssskkkiiiiiiksskmmmi.............",
    "....iiimmmmimimmiiimmmfffffffffffffifffiiifffffffmissssssskkiikbsssbbbbbbssssssssssssssssssssksssssskskiiiiiiikkkskmmmi.............",
    "......iiimimmimfiiimmmfffffffffffffifmiimfffmiiiiimkksssskiimmksssssssbsssssssssssssssssssssskssssssskkiiiikkksskkimmmi.............",
    ".......fiiifimmmmiimmmffffffffffffiiiimffmiiiffffmiiiikkiimmfmissssssssssskssssskkssssssssssskssssssskikkkksssssskimmmi.............",
    "......iiiimiiiimmmmmmmmffffffffiiiimffffiimffmimimffffiiimfffmmisssssssssksskkkiikssssssssskkkssssssskkkssssssskkimmmi..............",
    "....iiiffimimiiiiimmmmmffffffiiimiiiifmiwfmmimfmmfmmiifffiiiiifikssssssskiiiiimmmiiiikkkkikkkksssssskkksssssskiiimmmmi..............",
    "....ifffmimimmmmiiiiiimffmiiiiimmmmmiiiiimiifmfimimfmffmimmkimiiiikkkkkkimmmmmmmmmmfmmiiiiikkkkssssskksssssskfimmmmmii..............",
    "....mmffiiimmffffmmiiiiiiiiimmmmmffffffkiifiimiiifmfmwmmfmmimmiimmiiiiiiiimmmmmmmmmmmmfmmmfiiiikkkkkkssssskiifiiimmii...............",
    "....mmmmiiiffffffffffmfmmmmmmffffffffffmiiffffffmiiiimfmimmfmfmffmmmmmfffmiiiimfmmmmfmmmmmmmmmmffffmiikkkkifmimmiiiifmii............",
    "....mmmmiiimfffffffffffffffffffffffffmmmiimmffmfffffmiiiffmiiimimmfmmfmmimffwfmiimmmmmmmmmmmmmmmmmffffffiifffffffiifiiffi...........",
    "....mmmmiiimmmffffffffffffffffffffmmmmmmiimffmffmmfmffffmiimmiffiimmfmmmfmimmifffiimmmmmmmmmmmmmmfmmmmmmiimwffffiiiimfffii..........",
    "....mmmmiiimmmmmmffwffffffffffffmmmmmmmmiiiimmffmmmmfffffffmiimfiffmifwmiffmiffmmmimmmmmmmmmmmmmiiiifmmiffiiiiiiifmifiiimi..........",
    "....mmmmiiimmmmmmmmmffffffffffmmmmmmmmmmiimiiiiiimmfffmmffffffmmiiimfmfffmiiffmmmmimmmmmmmmmfmmiiffmimimfffffffffffimimmiiiiii......",
    "....mmmmiiiimmmmimmmmmfffwffmmmmmmmmmmmmiiimmmmiiiiimmffffmfmfffwfmiiimfiimfmmmmmimmmmmmmmmmmmmmiiffiiiffffffwffffmmimmmiifmmi......",
    "....mmmmmimimmmmiiiiiimmmfmmmmmmmmmmmmmmiiiiiiiiiiiiiiiiiimfmffffmffffiiiffmmmiiiimmmmmmmmmmmmmmmiiffimfffffffffffffiimiiifmmm......",
    "....immmmimiimmmimmmiiifmfmmmmmmmmmmmmmmiimmmimimimmmmiiiiiiiimmfffffffffmmmmiiimmmmmmiiiiiiimmmmmimfffmfffwfffffffmmiifiimfmm......",
    "....iiimmmimimmmiiimfmmfmfmmmmmmmmmmmmmfiiiiiimmiimmmmmmmmmmmiiiiimfffffmmmiiimmmmmmimfwwwwffmiimmmifffmffwffffffffmmifmimmmfi......",
    "....iiiiiiimiimmmmiiiiffmfmmmmmmmmmmmmiiiiimmmiiimmmmmmmmmmmmmmmmiiiimmfmiiimmmmmmifwfffmmmffwffimmimffmfffffffffffmmiiifmmfii......",
    "....mmmmiiiimiimmffmiiifmfmmmmmmmmmiiiimmmiiiiimmmmmmmmmmmmmmmmmmmmmmiiiiimmmmmmmifwfmmmmmmmmmfffimmimmimffffffffmmmmimmmfiimi......",
    "....mmmmmmmiimiiiimfffmmmfmmmmfmiiiimmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmiffmmfffffffmiffiffmiimmffffffffmmmimmmfimmmi......",
    "....mmmmmmmmiimmiiiiifimmfmmmmiiiimmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmimffffmmmmmmmffmimmmmiimmffffffmmmiimffimmmmi......",
    "....mmmmmmmmmiiimmiiiiiimwmiiiimmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmiiifffffffffmiimmmmmmiimmmmmmmmmiimfiimmmmmi......",
    "....mmmmmmmmmmmiiiiiiiiiiiiiimmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmiiiiiiiiiiiiimfmmmmmmiiiiiiiiiiimfimmmmmmmi......",
    "....mmmmmmmmmmmmmiiiiimmmimmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmiiiiiiiimmmmmmmmmmmmmiiiiiimfmimmmmmmmii......",
    "....mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfmmmmmmmmmmiii.......",
    "....mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfimmmmmmmmmii.........",
    "....immmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffimmmmmmmmiii..........",
    "....immmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfiimmmmmmmmiiii..........",
    "....mfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffmimmmmmmmmiiiimi..........",
    "....imimmmmmmmmmmmmmimmmmmmmmmmmmmimiimmmimmmmiimmmmmmmmmmmmmmmmimmmimmmmmmmmmmmmmmmmmmmiimmmmmmmmmmmiimmmimmmmmmmmiiiiimi..........",
    "....immmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmiimmmmmmiiimmmiii..........",
    "....immmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmiimmmmiiimmmmii.i..........",
    "....immmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmiimmmiiiimmmmmi.i..........",
    "....immmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmiimiiiimmmmmmmi.ii.........",
    "....immmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmiiimmiimmmmmmi.ii.........",
    "....iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiimmiimmmmmmmi.i..........",
    "....imiiiiiiiiiiiiiiimiiiiiiimmmmimimmmiiiimiiiiiimiiiiiiiiiimmmmimiiimmiiiiimmmmmmmmmmmmmmmmmiiiiiiiim.iiimmimmmmmmmmmi.i..........",
    "....imiiiiii...iiiiiiiiiiiiiiiiiii..ii.miiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiimiimimm....ii...m..iiiiiim...iiimmmmmmmmmmmmi.ii.........",
    "....i..............................................................................................i....iiimmmmmmmmmmmmi.i..........",
    "....i..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...................................................................................................i....iimmmmmmmmmmmmmi.ii.........",
    "...................................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...................................................................................................i....iimmmmmmmmmmmmmi.ii.........",
    "...................................................................................................i....iimmmmmmmmmmmmmi.ii.........",
    "..ii...............................................................................................i....iimmmmmmmmmmmmmi.ii.........",
    "..mii..............................................................................................i....iimmmmmmmmmmmmmi.ii.........",
    "...ii..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...ii..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...m...............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...ii..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...................................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...................................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...i...............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "..ii...............................................................................................i....iimmmmmmmmmmmmmi.ii.........",
    "...ii..............................................................................................i....iimmmmmmmmmmmmmi.ii.........",
    "...ii..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...ii..............................................................................................i....iimmmmmmmmmmmmmi.ii.........",
    "...mi..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "....i..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "....i..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "....i..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "....i..............................................................................................i....iimmmmmmmmmmmmmi.i..........",
    "...................................................................................................i....iiiiiiiiiiiiiiii.ii.........",
    "....................................................................................................................................",
    "....................................................................................................................................",
    "....................................................................................................................................",
  ],
};
